//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public DICHVU()
        {
            this.DONDATTIECs = new HashSet<DONDATTIEC>();
        }
    
        public int MA_DV { get; set; }
        public string TENDICHVU { get; set; }
        public Nullable<double> GIADV { get; set; }
    
        public virtual ICollection<DONDATTIEC> DONDATTIECs { get; set; }
    }
}
