//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATTIEC
    {
        public DONDATTIEC()
        {
            this.SANHCUOIs = new HashSet<SANHCUOI>();
            this.DICHVUs = new HashSet<DICHVU>();
        }
    
        public int MA_DD { get; set; }
        public int NHA_MA_NV { get; set; }
        public int TIM_MA_TC { get; set; }
        public int SAN_MA_SC { get; set; }
        public int KHA_MA_KH { get; set; }
        public int MEN_MA_MENU { get; set; }
        public string TENCODAU { get; set; }
        public string TENCHURE { get; set; }
        public Nullable<System.DateTime> NGAYCUOI { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<int> SOBAN { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public Nullable<int> MA_TC { get; set; }
        public Nullable<int> MA_SC { get; set; }
        public Nullable<int> MA_DV { get; set; }
        public Nullable<int> MA_NV { get; set; }
        public Nullable<int> MA_MENU { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual SANHCUOI SANHCUOI { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TIMETOCHUC TIMETOCHUC { get; set; }
        public virtual ICollection<SANHCUOI> SANHCUOIs { get; set; }
        public virtual ICollection<DICHVU> DICHVUs { get; set; }
    }
}
