//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DONDATTIECs = new HashSet<DONDATTIEC>();
        }
    
        public int MA_KH { get; set; }
        public string TENHO { get; set; }
        public Nullable<int> CMND { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<int> NAMSINH { get; set; }
        public string DIACHI { get; set; }
    
        public virtual ICollection<DONDATTIEC> DONDATTIECs { get; set; }
    }
}
