//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.DONDATTIECs = new HashSet<DONDATTIEC>();
        }
    
        public int MA_MENU { get; set; }
        public Nullable<int> TRA_MA_TM { get; set; }
        public Nullable<int> MON_MA_MN { get; set; }
        public Nullable<int> MON_MA_MC { get; set; }
        public Nullable<int> MON_MA_KV { get; set; }
        public Nullable<int> MON_MA_MS { get; set; }
        public Nullable<int> MON_MA_MP { get; set; }
        public string TENMENU { get; set; }
        public Nullable<double> GIATONG { get; set; }
        public Nullable<int> MA_KV { get; set; }
        public Nullable<int> MA_MP { get; set; }
        public Nullable<int> MA_MC { get; set; }
        public Nullable<int> MA_MS { get; set; }
        public Nullable<int> MA_MN { get; set; }
        public Nullable<int> MA_TM { get; set; }
    
        public virtual ICollection<DONDATTIEC> DONDATTIECs { get; set; }
        public virtual MONKHAIVI MONKHAIVI { get; set; }
        public virtual MONCHINH MONCHINH { get; set; }
        public virtual MONNUOC MONNUOC { get; set; }
        public virtual MONPHU MONPHU { get; set; }
        public virtual MONSUP MONSUP { get; set; }
        public virtual TRANGMIENG TRANGMIENG { get; set; }
    }
}
