//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatDonTiecEntities3 : DbContext
    {
        public DatDonTiecEntities3()
            : base("name=DatDonTiecEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<DONDATTIEC> DONDATTIECs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<MENU> MENUs { get; set; }
        public DbSet<MONCHINH> MONCHINHs { get; set; }
        public DbSet<MONKHAIVI> MONKHAIVIs { get; set; }
        public DbSet<MONNUOC> MONNUOCs { get; set; }
        public DbSet<MONPHU> MONPHUs { get; set; }
        public DbSet<MONSUP> MONSUPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<SANHCUOI> SANHCUOIs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TIMETOCHUC> TIMETOCHUCs { get; set; }
        public DbSet<TRANGMIENG> TRANGMIENGs { get; set; }
    }
}
