//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatTiec
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANHCUOI
    {
        public SANHCUOI()
        {
            this.DONDATTIECs = new HashSet<DONDATTIEC>();
        }
    
        public int MA_SC { get; set; }
        public Nullable<int> MA_DD { get; set; }
        public string TENSANH { get; set; }
        public Nullable<int> VITRI { get; set; }
        public Nullable<int> SUCCHUA { get; set; }
        public Nullable<int> SOBAN { get; set; }
        public Nullable<double> GIADAT { get; set; }
    
        public virtual ICollection<DONDATTIEC> DONDATTIECs { get; set; }
        public virtual DONDATTIEC DONDATTIEC { get; set; }
    }
}
